version: "3.8"

services:
  user-service:
    container_name: user-service
    build: .
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - MDB_HOST=mongo
      - MDB_PORT=27017
      - MDB_USER=admin
      - MDB_PASSWORD=admin
      - MDB_DB=userdb
  mongodb:
    container_name: mongo
    image: mongo
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=userdb

networks:
  default:
    driver: bridge